const faceCap_products = [
     {
          id: 0,
          productLink: 'round-neck1-products.html',
          image: 'images/round1.jpeg',
          alt: 'Shirt',
          producer: 'Adidas',
          productName: 'Shirt',
          price:150,
     },
     {
          id: 1,
          productLink: '',
          image: '',
          alt: '',
          producer: '',
          productName: '',
          price:250,
     },
     {
          id: 2,
          productLink: '',
          image: '',
          alt: '',
          producer: '',
          productName: '',
          price:75,
     },
     {
          id: 3,
          productLink: '',
          image: '',
          alt: '',
          producer: '',
          productName: '',
          price:250,
     },
     {
          id: 4,
          productLink: '',
          image: '',
          alt: '',
          producer: '',
          productName: '',
          price:250,
     },
     {
          id: 5,
          productLink: '',
          image: '',
          alt: '',
          producer: '',
          productName: '',
          price:250,
     },
     {
          id: 6,
          productLink: '',
          image: '',
          alt: '',
          producer: '',
          productName: '',
          price:170,
     },
     {
          id: 7,
          productLink: '',
          image: '',
          alt: '',
          producer: '',
          productName: '',
          price:250,
     },
     {
          id: 8,
          productLink: '',
          image: '',
          alt: '',
          producer: '',
          productName: '',
          price:0,
     },
     {
          id: 9,
          productLink: '',
          image: '',
          alt: '',
          producer: '',
          productName: '',
          price:0,
     },
]